### PR TITLE
Adds a CYK parser to lark.

### PR DESCRIPTION
**Pull request by ehudt**
The parser supports any CFG, with the following exceptions:
* The CFG's start rule can't appear on the right-hand-side of a rule
* There can't be any epsilon (empty) rules in the grammar

The parser converts the input grammar into a CYK-compatible grammar and returns a parse tree for the original grammar.

The parser also resolves ambiguities using the rule weight, and currently only returns the best (minimum-weight) parse.

### CODE REVIEW

**Comment by ehudt** [comment]
Note: This parser performs an order of magnitude faster on highly-ambiguous grammars compared to the current Earley implementation.

**Comment by erezsh** [comment]
Sounds fantastic! However,
1) It's failing the tests. It's probably not tested against the most recent version
2) I'll probably have to

**Comment by ehudt** [comment]
Hi! Thanks for the feedback. You are very welcome to restructure the code as you see fit.

I was instructed to add "Google LLC" to the LICENSE file if such exists in any project I contribute to. As far as I understand, this doesn't change the license (which remains MIT). Please let me know if this is an issue.

**Comment by erezsh** [comment]
Instructed by who? Anyway, I'm not going to give Google a copyright on my project, but I can put it specifically in the CYK parser. Is that good enough?

Alright, I'll try to get it to work and pass all the tests (except for those  the empty rules).

**Comment by ehudt** [comment]
I understand. Let me check and I'll get back you as soon as I can.

**Comment by ehudt** [comment]
Hi, 
It is OK to remove Google LLC from the LICENSE file.
Thanks for your patience!

**Comment by erezsh** [comment]
Great, so no problem. 
I'm already done adapting your code to the latest Lark version, along with other fixed for a more idiomatic code:
* hash is now calculated without repr
* support for both python 2 & 3
* indentation of 4 spaces

And other mainly cosmetic things. The code is essentially the same one you wrote. So my question here, is there anything you want to write in the module header? Right now I'm thinking along the lines of:

    Author:  https://github.com/ehudt
    Adaptation by Erez Shinan

If you want something more formal, or to add more details, etc. let me know

**Comment by erezsh** [comment]
p.s. there doesn't seem to be a formal way to mention contributors, so if you want it recorded in github, I'll send you my changes and you can open a new pull request (if you don't care, I'll just push it under my user)

**Comment by ehudt** [comment]
Hi!
Thanks for adapting to Lark idioms & style so quickly!
As for the header line - looks good.
I would be happy if my contribution is somehow recorded in github -- if that's not too much hassle.

**Comment by erezsh** [comment]
Hi, just in case you missed it, I opened a pull-request on your fork so you can merge it back in and get credit.

**Comment by ehudt** [comment]
Thanks for the heads-up. Done.

**Pull request merged**
