### PR TITLE
Add support for nearley @include

### PR DESCRIPTION
**Pull request by kasbah**
Solves the first part of #26

There is probably still a problem if you include the same file twice from different locations.

### CODE REVIEW

**Comment by erezsh** [comment]
The patch looks good! Any chance you can add a sample nearley grammar with the include directive?

**Comment by kasbah** [comment]
Where should that go, into [tools/nearley.py](https://github.com/erezsh/lark/blob/master/lark/tools/nearley.py#L166), or into the tests dir?

**Comment by erezsh** [comment]
Ideally into tests.

**Comment by kasbah** [comment]
Ok, I have made a unit testcases for the old css grammar test and the include. I added Nearley as a submodule of my own fork as I am currently [waiting for an include test to be merged](https://github.com/Hardmath123/nearley/pull/297) that I made use of. 

I will try and add a test for including the same file twice from different files to Nearley itself and then add a test case to Lark. How do you think Lark will handle that case as it stands?

**Comment by kasbah** [comment]
So, it currently fails the new multi-include test with:

```
  File "lark/load_grammar.py", line 621, in load_grammar
    raise GrammarError("Rule '%s' defined more than once" % name)
GrammarError: Rule 'n_b' defined more than once
```

**Comment by kasbah** [comment]
Ok, this should be good to go. Not sure if I should do anything about the style errors as I have been following what has been done in existing code.

**Comment by erezsh** [comment]
Thanks, merged!
I made a few small corrections, but overall I left it as you wrote it.

**Pull request merged**
